### ISSUE TITLE
lab 5 create reference files for kubernetes yaml files and reference them in lab.

### ISSUE THREAD

**Issue by dustymabe** [whitel/summit-2015-lab-15812#64]
If there is a slight mistake in the files (i'm talking whitespace) then the nulecule yaml parser blows up and gives a stack trace. This is not good for our customers to see (and may actually need to be an enhancement to nulecule to give better error messages the the user rather than just a stack trace). We should make them look at reference files for the pods/services as well and tell them to make sure there are no differences, even whitespace.

**Comment by dustymabe** [comment]
ok I now don't know if this was the issue or if actually being in /tmp is the issue. If I am in /tmp I get:

```
[root@summit-rhel-dev workspace]# cd /tmp/
[root@summit-rhel-dev tmp]# 
[root@summit-rhel-dev tmp]# atomic run wordpress-rhel7-atomicapp
docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name wordpress-rhel7-atomicapp -e NAME=wordpress-rhel7-atomicapp -e IMAGE=wordpress-rhel7-atomicapp wordpress-rhel7-atomicapp -v run /atomicapp
2015-06-04 03:46:20,773 - atomicapp.install - INFO - App name is wordpress-rhel7-atomicapp, will be populated to /atomicapp
2015-06-04 03:46:20,773 - atomicapp.nulecule_base - DEBUG - {'namespace': 'default', 'provider': 'kubernetes'}
2015-06-04 03:46:20,889 - atomicapp.nulecule_base - DEBUG - Output of docker images cmd: 40d9afa04a14

2015-06-04 03:46:20,889 - atomicapp.nulecule_base - DEBUG - Image wordpress-rhel7-atomicapp already present with id 40d9afa04a14. Use --update to re-pull.
2015-06-04 03:46:20,889 - atomicapp.nulecule_base - DEBUG - {'namespace': 'default', 'provider': 'kubernetes'}
2015-06-04 03:46:20,890 - atomicapp.install - DEBUG - Creating a container with name wordpress-rhel7-atomicapp-wUMyba
5323368e27012ce3e74f58f2618d441eba9e7e39205444fa90121e0c7e4bf3ec
2015-06-04 03:46:22,184 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-LBPlpn
2015-06-04 03:46:22,185 - atomicapp.install - DEBUG - ['docker', 'cp', 'wordpress-rhel7-atomicapp-wUMyba:/application-entity', '/tmp/nulecule-LBPlpn']
2015-06-04 03:46:22,549 - atomicapp.install - DEBUG - Application entity data copied to /tmp/nulecule-LBPlpn
wordpress-rhel7-atomicapp-wUMyba
2015-06-04 03:46:24,735 - atomicapp.install - DEBUG - Nulecule path for pulled image: /tmp/nulecule-LBPlpn/application-entity/Nulecule
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 89, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 70, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 20, in cli_run
    ae = Run(**vars(args))
  File "/usr/lib/python2.7/site-packages/atomicapp/run.py", line 64, in __init__
    install.install()
  File "/usr/lib/python2.7/site-packages/atomicapp/install.py", line 98, in install
    self.nulecule_base.loadMainfile(mainfile_path)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule_base.py", line 90, in loadMainfile
    self.mainfile_data = anymarkup.parse_file(path)
  File "/usr/lib/python2.7/site-packages/anymarkup/__init__.py", line 101, in parse_file
    return parse(f, format, encoding, force_types)
  File "/usr/lib/python2.7/site-packages/anymarkup/__init__.py", line 75, in parse
    raise AnyMarkupError(e)
anymarkup.AnyMarkupError: AnyMarkupError: caught <class 'yaml.scanner.ScannerError'>: while scanning for the next token
found character '\t' that cannot start any token
  in "<file>", line 9, column 1
```

if I am in /root/workspace:

```
[root@summit-rhel-dev workspace]# atomic run wordpress-rhel7-atomicapp
docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name wordpress-rhel7-atomicapp -e NAME=wordpress-rhel7-atomicapp -e IMAGE=wordpress-rhel7-atomicapp wordpress-rhel7-
atomicapp -v run /atomicapp
2015-06-04 03:47:42,211 - atomicapp.install - INFO - App name is wordpress-rhel7-atomicapp, will be populated to /atomicapp
2015-06-04 03:47:42,212 - atomicapp.install - INFO - Component data exist in /atomicapp, skipping population...
2015-06-04 03:47:42,221 - atomicapp.nulecule_base - DEBUG - Setting app id to summit-2015-wp
2015-06-04 03:47:42,221 - atomicapp.nulecule_base - DEBUG - Version check successful: specversion == 0.0.2
2015-06-04 03:47:42,221 - atomicapp.nulecule_base - DEBUG - No artifacts for mariadb
2015-06-04 03:47:42,221 - atomicapp.nulecule_base - INFO - Artifacts for mariadb present for these providers: 
2015-06-04 03:47:42,221 - atomicapp.nulecule_base - DEBUG - Provider: kubernetes
2015-06-04 03:47:42,222 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/kubernetes/wordpress-pod.yaml: OK
2015-06-04 03:47:42,222 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/kubernetes/wordpress-service.yaml: OK
2015-06-04 03:47:42,222 - atomicapp.nulecule_base - INFO - Artifacts for wordpress present for these providers: kubernetes
...
...
```

**Comment by aweiteka** [comment]
@dustymabe I think you're hitting a bug or at least very unexpected behavior. Basically you need to be in a clean directory if you want to use the files in the container. Otherwise it tries to deploy what you have in `pwd`. Fix won't make it in time for the lab.

**Comment by dustymabe** [comment]
@aweiteka you may be right that it is a bug. Can you execute lab5 exactly as is and tell me what you see?
